# enable display drivers
CONFIG_ZMK_DISPLAY=n

#EXT POWER
CONFIG_ZMK_EXT_POWER=y

#EC11 enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable SPI
CONFIG_SPI=y
#EXT POWER
CONFIG_ZMK_EXT_POWER=y